version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/ui
